name: DevSecOps Pipeline

on:
  push:
    branches:
      - main

jobs:

  security-checks:

    runs-on: ubuntu-latest

    steps:

      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        run: npm install

      - name: Run npm audit
        run: npm audit --audit-level=high || true

      - name: Install Semgrep
        run: pip install semgrep

      - name: Run Semgrep custom rules
        run: semgrep --config=.semgrep/password-rule.yml .

      - name: Build Docker image
        run: docker build -t devsecops-api .

      - name: Run Trivy scan
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: devsecops-api
          format: table
          severity: CRITICAL
          exit-code: 1